### ISSUE TITLE
Column name changes from RT PCR to NAAT 

### ISSUE THREAD

**Issue by Rwilli5** [annyrodriguez/analyze_COVID_delta#1]
### Description 

A few weeks ago, CDC changed the name of testing columns from RT PCR to NAAT tests. Note: PCR is a type of NAAT.  The change is insignificant in testing numbers, but for wrangle_CDC_20210803.R, this necessitates changing  column names e.g.,
from `viral_rt_pcr_lab_test_positivity_rate_previous_7_days` to `naat_positivity_rate_last_7_days`. The names are slight longer, but these are the names I create when I work with Community Profile Report.xlsx.

Otherwise, this happens 

### Current Output
<img width="571" alt="Screen Shot 2021-10-20 at 8 53 16 PM" src="https://user-images.githubusercontent.com/55334815/138192092-7dd1dc89-420c-4476-a25d-9c8999434c4f.png">

**Comment by Rwilli5** [comment]
@gabrielodom 

Was this the issue you were encountering or is it the absurd erroneously high positivity rate for MDC?

**Comment by gabrielodom** [comment]
@Rwilli5, this is the issue. Thank you.
@annyrodriguez, you already fixed this?

**Comment by annyrodriguez** [comment]
@gabrielodom @Rwilli5 - thanks for pointing this out, I'm in the process of fixing the issue.

**Comment by annyrodriguez** [comment]
The issue has been fixed. Thanks!
